pull_request_rules:
    - name: Automatic merge ⬇ on approval ✔
      conditions:
          - base=main
          - -closed
          - -conflict
          - label=mergeme
      actions:
          queue:
              commit_message_template: |
                  {{title}} (#{{number}})
                  {{body}}

                  Reviewed By: {{approved_reviews_by | join(', ')}}
                  GitHub Pull Request: https://github.com/production-assistant/mergify-test-repo/pull/{{number}}
              merge_method: squash
              name: default
          delete_head_branch:
              force: true

partition_rules:
  - name: fallback
    fallback_partition: true

  - name: projectA
    conditions:
      - files~=^projectA/

  - name: projectB
    conditions:
      - files~=^projectB/

queue_rules:
  - name: default
    queue_conditions:
      - or:
        - partition-name!=projectA
        - base=main
      - or:
        - partition-name!=projectB
        - base=main
      # - base=main
      # - -closed
      # - -conflict
    merge_method: merge
    speculative_checks: 3
