name: merge-queue-ci

on:
  pull_request:
    types: [
        # Default pull_request trigger types.
        opened,
        synchronize,
        reopened,
        # For linting labels. Note that a new job is kicked off per label
        # added or removed.
        labeled,
        unlabeled,
      ]

jobs:
  mq-ready-to-merge-verified:
    if: contains(github.head_ref, 'mq-bot')
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sleep for 30 seconds
        run: sleep 30
  mq-commit-integrity-verification:
    if: contains(github.head_ref, 'mq-bot')
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sleep for 30 seconds
        run: sleep 30
